/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.shinkle.SpringRestTutorial;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SpringRestTutorialApplication {

    public static void main(String[] args) {
        SpringApplication.run(SpringRestTutorialApplication.class, args);
    }

}
