/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.shinkle.SpringRestTutorial;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class SpringRestTutorialApplicationTests {

    @Test
    void contextLoads() {
    }

}
